// The textures each biome's day build asks for, in the order it asks: what texprep.js gets ready
// (from the texture cache or the paint workers) before the build starts. Generated by
// `node tools/texmanifest.mjs` from real builds of every day on a few seeds; a stale list only costs
// speed (a texture missing here is painted on the main thread when asked for, as it always was).
export const DAY_TEXTURES = {};
